apiVersion: v2
name: matchplane
description: Federated AI matching infrastructure services
type: application
version: 0.1.3
appVersion: 0.1.3
kubeVersion: '>=1.30.0-0'
annotations:
  artifacthub.io/license: LicenseRef-MatchPlane-Pending
